### PR TITLE
Create test.tsx

### PR DESCRIPTION
**Pull request by AKASHDIGHE2205**
Tesing pull request

### CODE REVIEW

**Comment by AKASHDIGHE2205** [comment]
testing the pull requst

**Comment by AKASHDIGHE2205** [comment]
reg

**Comment by Sagar-bhalerao** [comment]
its an updated file

**Review by Sagar-bhalerao — APPROVED** [review]

**Review by Sagar-bhalerao — COMMENTED** [review]
good its work all

**Pull request closed without merging**
